# Generated by Django 5.2.1 on 2025-05-13 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='career_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='career.careerpath'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='subjects_required',
            field=models.ManyToManyField(related_name='programs', to='career.subject'),
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='career.university'),
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together={('user', 'quiz')},
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('user', 'career_path')},
        ),
    ]
